// <auto-generated />
using IGI_lab1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IGI_lab1.Migrations
{
    [DbContext(typeof(CallContext))]
    [Migration("20180206195029_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IGI_lab1.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Dispatcher");

                    b.Property<string>("Number");

                    b.Property<string>("Route");

                    b.Property<int?>("TariffId");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TariffId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("IGI_lab1.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CarModelId");

                    b.Property<string>("Driver");

                    b.Property<DateTime>("LastTO");

                    b.Property<string>("Mechanic");

                    b.Property<double>("Mileage");

                    b.Property<string>("Number");

                    b.Property<DateTime>("YearCreation");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("IGI_lab1.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<string>("ModelName");

                    b.Property<string>("Specifications");

                    b.HasKey("Id");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("IGI_lab1.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<string>("Description");

                    b.Property<string>("TariffName");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("IGI_lab1.Call", b =>
                {
                    b.HasOne("IGI_lab1.Car", "Car")
                        .WithMany("Calls")
                        .HasForeignKey("CarId");

                    b.HasOne("IGI_lab1.Tariff", "Tariff")
                        .WithMany("Calls")
                        .HasForeignKey("TariffId");
                });

            modelBuilder.Entity("IGI_lab1.Car", b =>
                {
                    b.HasOne("IGI_lab1.CarModel", "CarModel")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
